# Generated by Django 5.0.7 on 2024-07-31 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
    ]
